# Generated by Django 2.0.3 on 2018-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True)),
                ('media_id', models.IntegerField(blank=True)),
                ('network', models.CharField(blank=True, max_length=255)),
                ('surface', models.CharField(blank=True, max_length=255)),
                ('track', models.CharField(blank=True, max_length=255)),
                ('date_id', models.IntegerField(blank=True)),
                ('event', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
