# Generated by Django 2.0.3 on 2018-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedvisionx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racematrix',
            name='date_id',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='racematrix',
            name='index',
            field=models.IntegerField(auto_created=True, blank=True, editable=False),
        ),
    ]
