# Generated by Django 2.0.3 on 2018-04-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedvisionx', '0003_auto_20180403_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racematrix',
            name='index',
        ),
    ]
