# Generated by Django 2.0.3 on 2018-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedvisionx', '0005_remove_racematrix_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='racematrix',
            name='media_id',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
