# Generated by Django 2.0.3 on 2018-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedvisionx', '0006_racematrix_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='racematrix',
            name='index',
            field=models.IntegerField(auto_created=True, blank=True, default=0),
        ),
    ]
